package normalize

var defaultAbbreviations = map[string]string{
	// teencode
	"ko":    "không",
	"k":     "không",
	"hok":   "không",
	"hem":   "không",
	"hông":  "không",
	"dc":    "được",
	"đc":    "được",
	"ns":    "nói",
	"nt":    "nhắn tin",
	"kb":    "không biết",
	"ntn":   "như thế nào",
	"wa":    "quá",
	"qá":    "quá",
	"wá":    "quá",
	"wa'":   "quá",
	"mk":    "mình",
	"mn":    "mọi người",
	"ng":    "người",
	"ngta":  "người ta",
	"trc":   "trước",
	"trog":  "trong",
	"j":     "gì",
	"r":     "rồi",
	"bn":    "bạn",
	"b":     "bạn",
	"bh":    "bao giờ",
	"ck":    "chồng",
	"vk":    "vợ",
	"c":     "chồng",
	"v":     "vợ",
	"ny":    "người yêu",
	"iu":    "yêu",
	"thjk":  "thích",
	"hum":   "hôm",
	"hnay":  "hôm nay",
	"hqua":  "hôm qua",
	"lm":    "làm",
	"đg":    "đang",
	"dag":   "đang",
	"zj":    "vậy",
	"zậy":   "vậy",
	"z":     "vậy",
	"dz":    "dậy",
	"ak":    "ừ",
	"uk":    "ừ",
	"ô kê":  "ok",
	"oke":   "ok",
	"vl":    "rất",
	"vcl":   "rất",
	"ad":    "admin",
	"ib":    "inbox",
	"rep":   "trả lời",
	"off":   "offline",
	"on":    "online",
	"avt":   "avatar",
	"kute":  "dễ thương",
	"sz":    "cỡ",
	"sr":    "xin lỗi",
	"tks":   "cảm ơn",
	"klq":   "không liên quan",
	"vđ":    "vấn đề",
	"sml":   "thua",
	"4rum":  "forum",
	"f.a":   "độc thân",
	"add":   "kết bạn",
	"2ny":   "người yêu",
	"pls":   "làm ơn",
	"plz":   "làm ơn",
	"omg":   "ôi trời ơi",
	"lol":   "cười lớn",
	"gr8":   "tuyệt vời",
	"4u":    "cho bạn",
	"3q":    "cảm ơn",
	"3n":    "cảm ơn",
	"bz":    "bận",
	"bzz":   "bận",
	"mún":   "muốn",
	"mun":   "muốn",
	"iu4e":  "yêu mãi mãi",
	"cheems": "shock",

	// others
	"tp":    "thành phố",
	"hcm":   "hồ chí minh",
	"hn":    "hà nội",
	"dn":    "đà nẵng",
	"sg":    "sài gòn",
	"đt":    "điện thoại",
	"dt":    "điện thoại",
	"gv":    "giáo viên",
	"hs":    "học sinh",
	"sv":    "sinh viên",
	"nv":    "nhân viên",
	"cty":   "công ty",
	"clb":   "câu lạc bộ",
	"nxb":   "nhà xuất bản",
	"htx":   "hợp tác xã",
	"ubnd":  "ủy ban nhân dân",
	"hđnd":  "hội đồng nhân dân",
	"bch":   "ban chấp hành",
	"btc":   "ban tổ chức",
	"thpt":  "trung học phổ thông",
	"thcs":  "trung học cơ sở",
	"đh":    "đại học",
	"cđ":    "cao đẳng",
	"tc":    "trung cấp",
	"cn":    "chủ nhật",
	"qh":    "quốc hội",
	"cp":    "chính phủ",
	"tw":    "trung ương",
}
